import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <int> counter: 42;
    callback request-increase-value();

    preferred-width: 300px;
    preferred-height: 200px;
    title: @tr("Rust GUI & CLI Template");
    icon: @image-url("../resources/logo/rust-logo-512x512-4060026730.png");

    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }

        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
    }
}
